server:
    port: 8085
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            initializationFailTimeout: -1
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.pv.demo.entity
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
